### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by oleersoy** [magi-project/wolf-m7m-cpuminer-V2#2]
When I try the build on Ubuntu 17.04 I get the following errors at the end of the build:
``` console
<artificial>:(.text+0x93b): undefined reference to `sph_sha224'
<artificial>:(.text+0x94a): undefined reference to `sph_sha256_close'
<artificial>:(.text+0xf7a): undefined reference to `sph_sha224'
<artificial>:(.text+0xf8d): undefined reference to `sph_sha256_close'
collect2: error: ld returned 1 exit status
Makefile:518: recipe for target 'minerd' failed
make[2]: *** [minerd] Error 1
make[2]: Leaving directory '/home/ole/Miners/wolf-m7m-cpuminer-V2'
Makefile:771: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ole/Miners/wolf-m7m-cpuminer-V2'
Makefile:422: recipe for target 'all' failed
make: *** [all] Error 2
```

Thoughts?

**Comment by kkkrackpot** [comment]
https://bitcointalk.org/index.php?topic=735170.5845
